name: Tag and deploy

on:
  push:
    branches:
      - qa*

jobs:
  extract_label:
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.split.outputs.label }}
    steps: 
      - uses: actions/checkout@v4
      - id: split
        env:
          BRANCH: ${{ github.event.ref }}
        run: |
          BRANCH_NAME=$( echo $BRANCH | rev | cut -d'/' -f 1 | rev )
          BRANCH_LABEL=$( echo $BRANCH_NAME | cut -d'-' -f2 )
          if [[ "$BRANCH_NAME" == "$BRANCH_LABEL" ]]; then BRANCH_LABEL=""; fi
          echo "label=$BRANCH_LABEL" >> $GITHUB_OUTPUT

  tag:
    needs: extract_label
    uses: roxom-markets/devops-scripts/.github/workflows/tag.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      repository: ${{ github.event.repository.name }}
      last_commit: ${{ github.event.after }}
      environment: 'qa'
      branch: ${{ github.event.ref }}
      label: ${{ needs.extract_label.outputs.label }}
    secrets: inherit

  create-tag:
    runs-on: ubuntu-latest
    needs: tag
    permissions:
        id-token: write
        contents: write
    steps:
      - uses: actions/checkout@v4
      - run: |
          git tag ${{ needs.tag.outputs.tag-qa }}
          git push origin ${{ needs.tag.outputs.tag-qa }}

  deploy:
    needs: [tag, create-tag]
    uses: roxom-markets/devops-scripts/.github/workflows/deploy-website.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      CONTAINER_IMAGE: ${{ github.event.repository.name }}:${{ needs.tag.outputs.tag-qa }}
      AWS_REGION: 'us-east-2'
      ENVIRONMENTAL_VARIABLES_FILE: ${{ vars.ENVIRONMENTAL_VARIABLES_FILE_QA }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_QA }}
      IAMROLE_GITHUB: ${{ secrets.IAMROLE_GITHUB_QA }}
      NEXT_PUBLIC_TURNSTILE_API_KEY: ""
      NPM_TOKEN: ${{ secrets.GH_TOKEN }}