name: Tag release candidate from release branch

on:
  push:
    branches:
      - 'release/**'

jobs:
  get_latest_tag:
    uses: roxom-markets/devops-scripts/.github/workflows/get_latest_tag.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      branch: ${{ github.event.ref }}
    secrets: inherit

  tag:
    needs: get_latest_tag
    uses: roxom-markets/devops-scripts/.github/workflows/tag.yml@main
    permissions:
      id-token: write
      contents: read
    with:
      repository: ${{ github.event.repository.name }}
      last_commit: ${{ github.event.after }}
      environment: 'rc'
      branch: ${{ github.event.ref }}
      last-rc-tag: ${{ needs.get_latest_tag.outputs.last_tag_rc }}
      label: ${{ needs.get_latest_tag.outputs.label }}
    secrets: inherit

  create-tag:
    runs-on: ubuntu-latest
    needs: tag
    permissions:
      id-token: write
      contents: write
    steps: 
      - uses: actions/checkout@v4
      - run: |
          git tag ${{ needs.tag.outputs.tag-rc }}
          git push origin ${{ needs.tag.outputs.tag-rc }}